// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyeqwkqwiltrufgkvgdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5ZXF3a3F3aWx0cnVmZ2t2Z2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2OTI4ODQsImV4cCI6MjA1MjI2ODg4NH0.WNaGPinoOsRNNP7_5ro2BbW0674KCuOjoBZ804P1jnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);